from fpdf import FPDF


class PDFReport(FPDF):
    def header(self):
        # 1. Logo / Title
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, 'Supply Chain Executive Summary', ln=True, align='C')
        self.ln(5)

    def footer(self):
        # 2. Page Number
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')


def clean_text(text):
    """
    Removes unsupported characters (emojis, special symbols)
    that crash the standard PDF font.
    """
    return text.encode('latin-1', 'replace').decode('latin-1')


def generate_pdf(metrics, ai_summary):
    """
    Generates a PDF file based on the dashboard metrics.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- SECTION 1: KEY METRICS ---
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, '1. Current Inventory Snapshot', ln=True)

    pdf.set_font('Helvetica', '', 10)
    items = [
        f"Average Monthly Demand: {metrics['avg_demand']} units",
        f"Volatility (Std Dev): {metrics['std_dev']} units",
        f"Optimal Order Quantity (EOQ): {metrics['eoq']} units",
        f"Current Safety Stock Target: {metrics['safety_stock']} units",
        f"Target Service Level: {metrics['sla'] * 100:.1f}%"
    ]

    for item in items:
        pdf.cell(0, 7, f"- {item}", ln=True)

    pdf.ln(10)

    # --- SECTION 2: AI INSIGHTS ---
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, '2. AI Risk Assessment', ln=True)

    pdf.set_font('Helvetica', 'I', 10)
    pdf.multi_cell(0, 7, "The following insights were generated by the AI Analysis engine based on live data:")
    pdf.ln(5)

    pdf.set_font('Courier', '', 9)
    safe_summary = clean_text(ai_summary)
    pdf.multi_cell(0, 6, safe_summary)

    pdf.ln(10)

    # --- SECTION 3: DISCLAIMER ---
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5,
                   "Generated by Digital Capacity Optimizer v2.7.5. This report is for internal planning purposes only.")

    # ✅ FIXED: Explicitly convert bytearray to bytes for Streamlit
    return bytes(pdf.output(dest='S'))