from fpdf import FPDF
import matplotlib

matplotlib.use('Agg')  # Force non-interactive backend
import matplotlib.pyplot as plt
import numpy as np
import tempfile
import os


class AcademicReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'LSP DIGITAL TWIN | RESEARCH ARTIFACT', 0, 1, 'C')
        self.set_font('Arial', 'I', 8)
        self.cell(0, 5, 'Stochastic Optimization & Multi-Modal Strategy Assessment', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Automated Decision Support System', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 10, f'  {title}', 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Times', '', 11)
        self.multi_cell(0, 6, body)
        self.ln()


def generate_pdf(metrics, ai_summary):
    pdf = AcademicReport()
    pdf.add_page()

    # 1. EXECUTIVE STRATEGIC SUMMARY
    pdf.chapter_title("1. EXECUTIVE STRATEGIC SUMMARY & RECOMMENDATIONS")
    pdf.chapter_body(ai_summary)

    # 2. COMPREHENSIVE METRICS GRID
    pdf.chapter_title("2. OPERATIONAL & STRATEGIC METRICS")
    pdf.set_font('Courier', '', 9)  # Slightly smaller font to fit more rows

    col_width = pdf.w / 2.2
    row_height = 7

    # FULL METRICS LIST (Matches Dashboard)
    data = [
        ("Service Lane", str(metrics.get('product_name', 'N/A'))),
        ("Transport Mode", str(metrics.get('transport_mode', 'Road'))),
        ("Avg Demand (Base)", f"{metrics['avg_demand']} units"),
        ("Return Volume", f"{metrics['return_vol']} units"),  # Added
        ("Total Throughput", f"{metrics['avg_demand'] + metrics['return_vol']} units"),  # Added
        ("Std Dev (Volatility)", f"{metrics['std_dev']} units"),
        ("Optimal Safety Stock", f"{metrics['safety_stock']} units"),
        ("Target Service Level", f"{metrics['sla']:.1%}"),
        ("Fill Rate Reliability", f"{metrics.get('reliability_score', 0):.1f}%"),  # Added
        ("Partner Dependency", f"{metrics['dependency_ratio']:.1f}%"),  # Added
        ("Outsourced Volume", f"{metrics.get('outsourced', 0)} units"),  # Added
        ("Resilience Score", f"{metrics.get('resilience_score', 0)}/100"),
        ("Customer Loyalty", f"{metrics['loyalty_score']}/100"),  # Added
        ("Est. CO2 Emissions", f"{metrics.get('co2_emissions', 0)} kg"),
        ("CO2 Saved (vs Road)", f"{metrics.get('co2_saved', 0)} kg")  # Added
    ]

    for label, value in data:
        pdf.cell(col_width, row_height, label, 1)
        pdf.cell(col_width, row_height, value, 1)
        pdf.ln()

    pdf.ln(10)

    # 3. VISUAL EVIDENCE
    pdf.chapter_title("3. STOCHASTIC CAPACITY DISTRIBUTION")
    pdf.set_font('Times', '', 10)
    pdf.write(5, "Figure 1: Probability Density Function (PDF) of demand versus allocated capacity limit.")
    pdf.ln(10)

    try:
        mu = metrics['avg_demand']
        sigma = metrics['std_dev']
        capacity = mu + metrics['safety_stock']
        if sigma <= 0: sigma = 1

        x = np.linspace(mu - 4 * sigma, mu + 4 * sigma, 100)
        y = (1 / (sigma * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x - mu) / sigma) ** 2)

        plt.figure(figsize=(7, 4))
        plt.plot(x, y, 'b-', linewidth=2, label='Demand PDF')

        x_fill = np.linspace(mu - 4 * sigma, capacity, 100)
        y_fill = (1 / (sigma * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x_fill - mu) / sigma) ** 2)
        plt.fill_between(x_fill, y_fill, color='green', alpha=0.3, label='Fulfilled Demand')

        x_risk = np.linspace(capacity, mu + 4 * sigma, 50)
        y_risk = (1 / (sigma * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x_risk - mu) / sigma) ** 2)
        plt.fill_between(x_risk, y_risk, color='red', alpha=0.3, label='Stockout Risk')

        plt.axvline(capacity, color='k', linestyle='--', label=f'Capacity Limit ({int(capacity)})')

        plt.title('Capacity Coverage vs. Demand Uncertainty')
        plt.xlabel('Volume (Pallets)')
        plt.ylabel('Probability Density')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.tight_layout()

        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
            plt.savefig(tmp.name, dpi=150)
            tmp_path = tmp.name

        pdf.image(tmp_path, x=20, w=170)
        plt.close()
        os.unlink(tmp_path)

    except Exception as e:
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, f"Error generating chart: {str(e)}", 0, 1)
        pdf.set_text_color(0, 0, 0)

    return bytes(pdf.output(dest='S'))