from fpdf import FPDF


class PDFReport(FPDF):
    def header(self):
        # 1. Professional Header
        self.set_font('Helvetica', 'B', 16)
        self.cell(0, 10, 'LSP Strategic Resilience Report', ln=True, align='C')
        self.set_font('Helvetica', 'I', 10)
        self.cell(0, 6, 'Digital Capacity Twin | v3.0.0 Research Artifact', ln=True, align='C')
        self.ln(10)

        # Horizontal Line
        self.line(10, 30, 200, 30)
        self.ln(5)

    def footer(self):
        # 2. Page Number & Branding
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Wallenburg-Hegde Logic Engine', align='C')


def clean_text(text):
    """
    Removes unsupported characters (emojis, special symbols)
    that crash the standard PDF font.
    """
    if not isinstance(text, str):
        return str(text)
    # Replace common bullets that fail in Latin-1
    text = text.replace("•", "-").replace("—", "-")
    return text.encode('latin-1', 'replace').decode('latin-1')


def generate_pdf(metrics, ai_summary):
    """
    Generates a PhD-grade PDF report including Resilience and Cooperation metrics.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- META DATA ---
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, f"Service Lane ID: {clean_text(metrics.get('product_name', 'Aggregate'))}", ln=True)
    pdf.cell(0, 6, f"Target SLA: {metrics.get('sla', 0.95) * 100:.1f}%", ln=True)
    pdf.ln(5)

    # --- SECTION 1: NETWORK RESILIENCE SCORECARD ---
    pdf.set_fill_color(240, 240, 240)  # Light Gray Background
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, '1. Network Resilience Profile', ln=True, fill=True)
    pdf.ln(2)

    pdf.set_font('Helvetica', '', 10)

    # Logic to describe the score textually
    r_score = metrics.get('resilience_score', 0)
    if r_score > 80:
        status = "ROBUST (Low Risk)"
    elif r_score > 50:
        status = "MODERATE (Monitor Closely)"
    else:
        status = "CRITICAL (High Vulnerability)"

    items_resilience = [
        f"Resilience Index: {r_score}/100 [{status}]",
        f"Partner Dependency Ratio: {metrics.get('dependency_ratio', 0)}%",
        f"Supply Volatility (Sigma LT): {metrics.get('lead_time_risk', 0.2)}",
        f"Safety Buffer Coverage: {metrics.get('safety_stock', 0)} pallets"
    ]

    for item in items_resilience:
        pdf.cell(0, 6, f"- {item}", ln=True)
    pdf.ln(5)

    # --- SECTION 2: OPERATIONAL FLOW & COOPERATION ---
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, '2. Capacity & Horizontal Cooperation', ln=True, fill=True)
    pdf.ln(2)

    pdf.set_font('Helvetica', '', 10)

    # Calculate totals for the report
    total_flow = metrics.get('avg_demand', 0)
    outsourced = metrics.get('outsourced', 0)
    internal = total_flow - outsourced
    returns = metrics.get('return_vol', 0)

    items_ops = [
        f"Total Throughput Volume: {total_flow} units",
        f"  > Internal Handling: {internal} units",
        f"  > Outsourced to Competitor: {outsourced} units (Overflow)",
        f"Reverse Logistics Load (Returns): {returns} units",
        f"Est. Service Reliability: {metrics.get('reliability_score', 'N/A')}%"
    ]

    for item in items_ops:
        pdf.cell(0, 6, f"- {item}", ln=True)
    pdf.ln(10)

    # --- SECTION 3: AI EXECUTIVE SUMMARY ---
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, '3. AI Strategic Analysis', ln=True, fill=True)
    pdf.ln(2)

    pdf.set_font('Helvetica', 'I', 10)
    pdf.multi_cell(0, 6, "The following analysis was generated using the 'Pixels to Premiums' logic framework:")
    pdf.ln(2)

    pdf.set_font('Courier', '', 9)
    safe_summary = clean_text(ai_summary)
    pdf.multi_cell(0, 5, safe_summary)

    pdf.ln(10)

    # --- SECTION 4: DISCLAIMER ---
    pdf.set_y(-30)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4,
                   "Generated by LSP Digital Capacity Twin. This report operationalizes the concepts of Horizontal Cooperation and Supply Chain Resilience for academic research purposes.")

    return bytes(pdf.output(dest='S'))