name: üêõ Empirical Simulation Anomaly
description: Report a deviation between the Digital Twin output and expected theoretical/financial models.
title: "[Anomaly]: "
labels: ["bug", "empirical-validation", "stochastic-model"]
assignees:
  - sandesh-s-hegde
body:
  - type: markdown
    attributes:
      value: |
        ### üëã Research Validation Protocol
        Thank you for stress-testing the LSP Digital Capacity Twin. Please provide detailed parameters to assist with replicating the stochastic anomaly.

  - type: input
    id: contact
    attributes:
      label: Academic / Professional Contact
      description: How can we reach you if we need to discuss the underlying mathematics?
      placeholder: ex. researcher@lmu.de
    validations:
      required: false

  - type: dropdown
    id: module
    attributes:
      label: Affected Research Module
      description: Which part of the Digital Twin produced the anomaly?
      options:
        - FinTech: Climate Risk & ETS Pricing (GBM)
        - Strategy: Global Sourcing & CBAM Taxes
        - Platform Economics: Horizontal Cooperation
        - Operations: Monte Carlo Risk Engine
        - Geospatial: Network Routing & API
      default: 0
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Empirical Deviation
      description: Describe the anomaly. What did you expect to happen based on the theoretical models (e.g., Geometric Brownian Motion, Newsvendor, etc.)?
      placeholder: "Example: The Carbon Value at Risk (CVaR) at 95% did not scale correctly when ETS market volatility (œÉ) was increased to 0.60..."
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Artifact Version
      description: What version of the Digital Twin are you auditing?
      options:
        - v4.2.6 (Current Academic/Enterprise Release)
        - v4.0.x (Legacy)
        - Local / Sandbox Build
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser Environment
      description: Which browser are you using to access the Streamlit dashboard?
      multiple: true
      options:
        - Google Chrome
        - Firefox
        - Safari
        - Microsoft Edge
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Traceback / Matrix Errors
      description: Please paste any Python tracebacks, Plotly rendering errors, or NumPy dimension mismatches here.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Research Integrity
      description: By submitting this issue, you agree to follow the project's Contributor Covenant (v2.1).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
